[package]
name = "p2p-game-engine"
version = "0.1.0"
edition = "2024"
rust-version = "1.91.0"

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
anyhow = "^1"
tokio = { version = "1" }
iroh = "0.95"
iroh-docs = { version = "0.95.0" }
iroh-blobs = { version = "0.97" }
iroh-gossip = { version = "0.95" }
bytes = "1"
num_cpus = { version = "1.15.0" }
tokio-util = { version = "0.7" }
rand = "0.9.2"
tempfile = "3.20.0"
n0-future = "0.3"
postcard = { version = "1.1.3", features = ["use-std"] }
